<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MwCommon\Module'                                 => __DIR__ . '/Module.php',
    'MwCommon\Filter\ParagraphToHtml'                 => __DIR__ . '/src/MwCommon/Filter/ParagraphToHtml.php',
    'MwCommon\Validator\Country'                      => __DIR__ . '/src/MwCommon/Validator/Country.php',
    'MwCommon\Validator\CountryRegion'                => __DIR__ . '/src/MwCommon/Validator/CountryRegion.php',
    'MwCommon\Validator\Ein'                          => __DIR__ . '/src/MwCommon/Validator/Ein.php',
    'MwCommon\Validator\Iban'                         => __DIR__ . '/src/MwCommon/Validator/Iban.php',
    'MwCommon\Validator\PhoneNumber'                  => __DIR__ . '/src/MwCommon/Validator/PhoneNumber.php',
    'MwCommon\Validator\RoutingTransitNumber'         => __DIR__ . '/src/MwCommon/Validator/RoutingTransitNumber.php',
    'MwCommon\Validator\Ssn'                          => __DIR__ . '/src/MwCommon/Validator/Ssn.php',
    'MwCommonTest\Validator\CountryRegionTest'        => __DIR__ . '/tests/MwCommonTest/Validator/CountryRegionTest.php',
    'MwCommonTest\Validator\CountryTest'              => __DIR__ . '/tests/MwCommonTest/Validator/CountryTest.php',
    'MwCommonTest\Validator\EinTest'                  => __DIR__ . '/tests/MwCommonTest/Validator/EinTest.php',
    'MwCommonTest\Validator\IbanTest'                 => __DIR__ . '/tests/MwCommonTest/Validator/IbanTest.php',
    'MwCommonTest\Validator\PhoneNumberTest'          => __DIR__ . '/tests/MwCommonTest/Validator/PhoneNumberTest.php',
    'MwCommonTest\Validator\RoutingTransitNumberTest' => __DIR__ . '/tests/MwCommonTest/Validator/RoutingTransitNumber.php',
    'MwCommonTest\Validator\SsnTest'                  => __DIR__ . '/tests/MwCommonTest/Validator/SsnTest.php',
);
