<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MwCommon\Module'                         => __DIR__ . '/Module.php',
    'MwCommon\Filter\ParagraphToHtml'         => __DIR__ . '/src/MwCommon/Filter/ParagraphToHtml.php',
    'MwCommon\Validator\Country'              => __DIR__ . '/src/MwCommon/Validator/Country.php',
    'MwCommon\Validator\CountryRegion'        => __DIR__ . '/src/MwCommon/Validator/CountryRegion.php',
    'MwCommon\Validator\Iban'                 => __DIR__ . '/src/MwCommon/Validator/Iban.php',
    'MwCommon\Validator\RoutingTransitNumber' => __DIR__ . '/src/MwCommon/Validator/RoutingTransitNumber.php',
    'MwCommon\View\Helper\Gravatar'           => __DIR__ . '/src/MwCommon/View/Helper/Gravatar.php',
);